# Generated by Django 6.0.2 on 2026-02-14 15:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TorrentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('info_hash', models.CharField(max_length=40, unique=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('checking', 'Checking'), ('downloading', 'Downloading'), ('seeding', 'Seeding'), ('paused', 'Paused'), ('error', 'Error'), ('completed', 'Completed')], default='queued', max_length=20)),
                ('progress', models.FloatField(default=0.0)),
                ('download_speed', models.IntegerField(default=0, help_text='Bytes per second')),
                ('upload_speed', models.IntegerField(default=0, help_text='Bytes per second')),
                ('total_size', models.BigIntegerField(default=0)),
                ('eta', models.IntegerField(default=0, help_text='Estimated time in seconds')),
                ('save_path', models.CharField(max_length=1024)),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
